const icons = {
  home: "fas fa-home",
  search: "fas fa-search",
  library: "fas fa-compact-disc",
  download: "fas fa-cloud-download-alt",
  like: "far fa-heart",
  window: "far fa-window-maximize",
  shuffle: "fas fa-random",
  backward: "fas fa-backward",
  forward: "fas fa-forward",
  play: "far fa-play-circle",
  repeat: "fas fa-redo-alt",
  volume: "fas fa-volume-up",
  desktop: "fas fa-desktop",
  musicList: "fas fa-list",
  facebook: "fab fa-facebook",
  apple: "fab fa-apple",
  lock: "fas fa-lock",
};
